### ISSUE TITLE
Error when merging compound condition with implicit reference to boolean column in Rails 7.0.8

### ISSUE THREAD

**Issue by owst** [rzane/baby_squeel#130]
## Issue

Attempting to `merge` two relations where one has an implicit reference to a boolean column works in Rails 7.0.7, but raises an error in Rails 7.0.8 and above. Assuming a table of posts:
```ruby
  create_table :posts, force: true do |t|
    t.integer :view_count
    t.boolean :published
    t.integer :reference_count
  end
```
then we can find viewed-and-published posts with
```ruby
viewed_and_published = Posts.where.has { (view_count >= 1) & published }
```
and can find posts that are referenced at least twice with:
```ruby
referenced = Posts.where.has { reference_count >= 2 }
```
and can then find viewed-and-published posts that are referenced at least twice with:
```ruby
viewed_and_published.merge(referenced)
```

In Rails 7.0.7 this generates the expected SQL:
```
SELECT "posts".* FROM "posts" WHERE "posts"."view_count" >= 1 AND "posts"."published" AND "posts"."reference_count" >= 2
```
However in Rails 7.0.8 this raises an error:
```
NoMethodError: undefined method `fetch_attribute' for #<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x000000010f9ff2f8 @name="posts", @klass=Post(id: integer, view_count: integer, published: boolean, reference_count: integer), @type_caster=#<ActiveRecord::TypeCaster::Map:0x000000010f9feb78 @klass=Post(id: integer, view_count: integer, published: boolean, reference_count: integer)>, @table_alias=nil>, name="published">

        children.any? && children.all? { |child| child.fetch_attribute(&block) }
                                                      ^^^^^^^^^^^^^^^^
    /Users/owst/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activerecord-7.0.8/lib/arel/nodes/and.rb:22:in `block in fetch_attribute'
    /Users/owst/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activerecord-7.0.8/lib/arel/nodes/and.rb:22:in `all?'
    /Users/owst/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activerecord-7.0.8/lib/arel/nodes/and.rb:22:in `fetch_attribute'
    /Users/owst/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activerecord-7.0.8/lib/arel.rb:52:in `fetch_attribute'
    /Users/owst/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activerecord-7.0.8/lib/active_record/relation/where_clause.rb:138:in `extract_attribute'
    /Users/owst/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activerecord-7.0.8/lib/active_record/relation/where_clause.rb:163:in `block in predicates_unreferenced_by'
    /Users/owst/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activerecord-7.0.8/lib/active_record/relation/where_clause.rb:162:in `reject'
    /Users/owst/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activerecord-7.0.8/lib/active_record/relation/where_clause.rb:162:in `predicates_unreferenced_by'
```
When working on a reproduction of this issue I ended up creating #129 - it's quite possible that however that issue is resolved will also resolve this issue, but I wanted to record the error/backtrace in case others hit the same issue.

#### Reproduction

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "= 7.0.7"
  gem "baby_squeel", "= 3.0.0"
  gem "sqlite3"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.integer :view_count
    t.boolean :published
    t.integer :reference_count
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_association_stuff
    post = Post.create!(view_count: 1, published: true, reference_count: 2)

    referenced = Post.where.has { reference_count >= 2 }
    viewed_and_published = Post.where.has { (view_count >= 1) & published }

    # Raises on Rails 7.0.8 and above
    assert_equal viewed_and_published.merge(referenced), [post]
  end
end
```
